public with sharing class Constants{
	public static final String ICON_S = 'icon_s.png';
	public static final String ICON_D = 'icon_d.png';
	public static final String ICON_A = 'icon_a.png';

	public static final String PARTIALLY_USED = 'Partially Used';
	public static final String USED           = 'Used';
	public static final String NOT_USE        = 'Not Use';

	public static final String FIELD_VAL  = 'Field';
	public static final String OBJECT_VAL = 'Object';
	public static final String NONE = '--None--';
	public static final String SPONSOR         = 'Sponsor';
	public static final String DECISION_MAKER  = 'Decision Maker';
	public static final String RISK_LEVEL      = 'Risk Level';
	public static final String DECISION_IMPACT = 'Decision Impact';

	public static final String DMGT                     = 'DMGT';
	public static final String RISK_ASSESSMENT_TOOL     = 'Risk Assessment Tool';
	public static final String WEIGHTED_RANKINGS_MATRIX = 'Weighted Rankings Matrix';
	public static final String DECISION_EXECUTION_TOOL  = 'Decision Execution Tool';
	public static final String DECISION_EVALUATION_TOOL = 'Decision Evaluation Tool';
	public static final String PROJECT_VIEW_TOOL        = 'Project View';

	public static final String HOME_PAGE_URL                   = 'home/home.jsp';
	public static final String ADOPTION_DASHBOARDS             = 'Adoption_Dashboards';
	public static final String CLI_RECORDTYPE_MASTER_RECORD    = 'Master Record';
	public static final String CLI_RECORDTYPE_PROJECT_INSTANCE = 'Project Instance';

	public static final String DECISION    = 'Decision';
	public static final String ALL         = 'All';

	public static final String PHASE_MASTER_RECORD_TYPE_NAME    = 'Master Record';
	public static final String PHASE_PROJECT_INSTANCE_TYPE_NAME = 'Project Instance';

	public static final String USER_ACTIVITY_TRACKING_VIEW    = 'View';
	public static final String USER_ACTIVITY_TRACKING_UPDATE  = 'Update';
}